<?php

namespace App\Modules\Parla\Database\Seeds;

use Illuminate\Database\Seeder;
use DB;
use App\Modules\Parla\Repositories\TipoProposicaoRepository;
use App\Modules\Parla\Repositories\TipoConsultaRepository;
use App\Modules\Parla\Repositories\TipoPosicaoRepository;
use App\Modules\Parla\Repositories\TipoSituacaoRepository;

class ParlaDatabaseSeeder extends Seeder
{

    private $tipoProposicaoRepository;
    private $tipoConsultaRepository;
    private $tipoPosicaoRepository;

    public function __construct(TipoProposicaoRepository $tipoProposicaoRepository, TipoConsultaRepository $tipoConsultaRepository, TipoPosicaoRepository $tipoPosicaoRepository, TipoSituacaoRepository $tipoSituacaoRepository)
    {
        $this->tipoProposicaoRepository = $tipoProposicaoRepository;
        $this->tipoConsultaRepository = $tipoConsultaRepository;
        $this->tipoPosicaoRepository = $tipoPosicaoRepository;
        $this->tipoSituacaoRepository = $tipoSituacaoRepository;
    }
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //SISTEMA
        $this->call(ParlaConfigSeeder::class);
        
        //TABELAS
        $this->tipoProposicaoRepository->firstOrCreate(
            [
                'sg_tipo_proposicao' => 'PDS',
                'tx_tipo_proposicao' => 'PROJETO DE DECRETO LEGISLATIVO (SF)',
                'sg_casa_origem' => 'SF',
            ]
        );

        $this->tipoProposicaoRepository->firstOrCreate(
            [
                'sg_tipo_proposicao' => 'PEC',
                'tx_tipo_proposicao' => 'PROPOSTA DE EMENDA À CONSTITUIÇÃO',
                'sg_casa_origem' => 'SF',
            ]
        );

        $this->tipoProposicaoRepository->firstOrCreate(
            [
                'sg_tipo_proposicao' => 'PLS',
                'tx_tipo_proposicao' => 'PROJETO DE LEI DO SENADO',
                'sg_casa_origem' => 'SF',
            ]
        );

        $this->tipoProposicaoRepository->firstOrCreate(
            [
                'sg_tipo_proposicao' => 'PLV',
                'tx_tipo_proposicao' => 'PROJETO DE LEI DE CONVERSÃO (revisora)',
                'sg_casa_origem' => 'SF',
            ]
        );

        $this->tipoProposicaoRepository->firstOrCreate(
            [
                'sg_tipo_proposicao' => 'PRS',
                'tx_tipo_proposicao' => 'PROJETO DE RESOLUÇÃO DO SENADO',
                'sg_casa_origem' => 'SF',
            ]
        );

        $this->tipoProposicaoRepository->firstOrCreate(
            [
                'sg_tipo_proposicao' => 'MPV',
                'tx_tipo_proposicao' => 'MEDIDA PROVISÓRIA',
                'sg_casa_origem' => 'CD',
            ]
        );

        $this->tipoProposicaoRepository->firstOrCreate(
            [
                'sg_tipo_proposicao' => 'PDC',
                'tx_tipo_proposicao' => 'PROJETO DE DECRETO LEGISLATIVO (CD)',
                'sg_casa_origem' => 'CD',
            ]
        );

        $this->tipoProposicaoRepository->firstOrCreate(
            [
                'sg_tipo_proposicao' => 'PEC',
                'tx_tipo_proposicao' => 'PROPOSTA DE EMENDA À CONSTITUIÇÃO',
                'sg_casa_origem' => 'CD',
            ]
        );

        $this->tipoProposicaoRepository->firstOrCreate(
            [
                'sg_tipo_proposicao' => 'PFC',
                'tx_tipo_proposicao' => 'PROPOSTA DE FISCALIZAÇÃO E CONTROLE',
                'sg_casa_origem' => 'CD',
            ]
        );

        $this->tipoProposicaoRepository->firstOrCreate(
            [
                'sg_tipo_proposicao' => 'PL',
                'tx_tipo_proposicao' => 'PROJETO DE LEI',
                'sg_casa_origem' => 'CD',
            ]
        );

        $this->tipoProposicaoRepository->firstOrCreate(
            [
                    'sg_tipo_proposicao' => 'PLP',
                'tx_tipo_proposicao' => 'PROJETO DE LEI COMPLEMENTAR',
                'sg_casa_origem' => 'CD',
            ]
        );

        $this->tipoProposicaoRepository->firstOrCreate(
            [
                'sg_tipo_proposicao' => 'PLV',
                'tx_tipo_proposicao' => 'PROJETO DE LEI DE CONVERSÃO',
                'sg_casa_origem' => 'CD',
            ]
        );

        $this->tipoProposicaoRepository->firstOrCreate(
            [
                'sg_tipo_proposicao' => 'PRC',
                'tx_tipo_proposicao' => 'PROJETO DE RESOLUÇÃO (CD)',
                'sg_casa_origem' => 'CD',
            ]
        );


        $tipos_consulta = [
            [ 'tx_tipo_consulta' => 'ADITAMENTO' ],
            [ 'tx_tipo_consulta' => 'ADITAMENTO CONSIDERANDO EMENDAS' ],
            [ 'tx_tipo_consulta' => 'ADITAMENTO CONSIDERANDO PARECER' ],
            [ 'tx_tipo_consulta' => 'ADITAMENTO CONSIDERANDO SUBSTITUTIVO' ],
            [ 'tx_tipo_consulta' => 'ARQUIVADO' ],
            [ 'tx_tipo_consulta' => 'AVISO/MF' ],
            [ 'tx_tipo_consulta' => 'AVISO MINISTRO' ],
            [ 'tx_tipo_consulta' => 'CONS. C/PARECER' ],
            [ 'tx_tipo_consulta' => 'CONS. C/PARECER EXTERNO' ],
            [ 'tx_tipo_consulta' => 'CONS. C/POS. DIVERGENTES' ],
            [ 'tx_tipo_consulta' => 'CONS. C/SUB.EMEN E SUBSTI' ],
            [ 'tx_tipo_consulta' => 'CONS. C/SUBST. AS EMENDAS' ],
            [ 'tx_tipo_consulta' => 'CONS. C/SUBST. E EMENDAS' ],
            [ 'tx_tipo_consulta' => 'CONS. EMENDAS E PARECER' ],
            [ 'tx_tipo_consulta' => 'CONSIDERANDO EMENDA AO SUBSTITUTIVO' ],
            [ 'tx_tipo_consulta' => 'CONSIDERANDO EMENDA E SUBSTITUTIVO' ],
            [ 'tx_tipo_consulta' => 'CONSIDERANDO EMENDAS' ],
            [ 'tx_tipo_consulta' => 'CONSIDERANDO EMENDAS E SUBSTITUTIVO' ],
            [ 'tx_tipo_consulta' => 'CONSIDERANDO FINANCIAMENTO PÚBLICO' ],
            [ 'tx_tipo_consulta' => 'CONSIDERANDO O PL , SUBSTITUTIVO E EMENDA' ],
            [ 'tx_tipo_consulta' => 'CONSIDERANDO O SUBSTITUTIVO' ],
            [ 'tx_tipo_consulta' => 'CONSIDERANDO O TEXTO APROVADO NA CD' ],
            [ 'tx_tipo_consulta' => 'CONSIDERANDO PARECER DA CEF' ],
            [ 'tx_tipo_consulta' => 'CONSIDERANDO PARECERES DIVERSOS' ],
            [ 'tx_tipo_consulta' => 'CONSIDERANDO TEXTO APROVADO CFT' ],
            [ 'tx_tipo_consulta' => 'CONS. S/EMENDAS' ],
            [ 'tx_tipo_consulta' => 'CONS. S/TEXTO APROV.SF' ],
            [ 'tx_tipo_consulta' => 'CONSULTA' ],
            [ 'tx_tipo_consulta' => 'CONSULTA CONSIDERADO PL E AS EMENDAS E AS SUBEMENDAS' ],
            [ 'tx_tipo_consulta' => 'CONSULTA CONSIDERANDO EMENDAS' ],
            [ 'tx_tipo_consulta' => 'CONSULTA CONSIDERANDO EMENDA SUBSTITUTIVA GLOBAL' ],
            [ 'tx_tipo_consulta' => 'CONSULTA CONSIDERANDO O PROJETO E MINUTA' ],
            [ 'tx_tipo_consulta' => 'CONSULTA CONSIDERANDO O PROJETO E SUBSTITUTIVO' ],
            [ 'tx_tipo_consulta' => 'CONSULTA CONSIDERANDO PARECER' ],
            [ 'tx_tipo_consulta' => 'CONSULTA CONSIDERANDO PARECER E SUBSTITUTIVO' ],
            [ 'tx_tipo_consulta' => 'CONSULTA CONSIDERANDO PL E EMENDA SUBSTITUTIVA' ],
            [ 'tx_tipo_consulta' => 'CONSULTA CONSIDERANDO PL, EMENDA E SUBEMENDA' ],
            [ 'tx_tipo_consulta' => 'CONSULTA CONSIDERANDO PL, EMENDAS, SUBSTITUTIVOS' ],
            [ 'tx_tipo_consulta' => 'CONSULTA CONSIDERANDO PL E RELATÓRIO' ],
            [ 'tx_tipo_consulta' => 'CONSULTA CONSIDERANDO PL E SUBEMENDA' ],
            [ 'tx_tipo_consulta' => 'CONSULTA CONSIDERANDO PL OS, APENSADOS E EMENDAS' ],
            [ 'tx_tipo_consulta' => 'CONSULTA CONSIDERANDO PL, SUBSTITUTIVO E EMENDA' ],
            [ 'tx_tipo_consulta' => 'CONSULTA CONSIDERANDO PROJETO E EMENDA' ],
            [ 'tx_tipo_consulta' => 'CONSULTA CONSIDERANDO PROJETO E O SUBSTITUTIVO' ],
            [ 'tx_tipo_consulta' => 'CONSULTA CONSIDERANDO PROJETO E PARECER' ],
            [ 'tx_tipo_consulta' => 'CONSULTA CONSIDERANDO PROJETO E RELATÓRIO' ],
            [ 'tx_tipo_consulta' => 'CONSULTA CONSIDERANDO SUBEMENDA SUBSTITUTIVA GLOBAL' ],
            [ 'tx_tipo_consulta' => 'CONSULTA CONSIDERANDO SUBSTITUTIVO' ],
            [ 'tx_tipo_consulta' => 'CONSULTA CONSIDERANDO SUBSTITUTIVO E EMENDAS' ],
            [ 'tx_tipo_consulta' => 'CONSULTA CONSIDERANDO SUBSTITUTIVO E PARECER' ],
            [ 'tx_tipo_consulta' => 'CONSULTA C/ TC LEI RP' ],
            [ 'tx_tipo_consulta' => 'CONSULTA O TEXTO APROVADO NA CD' ],
            [ 'tx_tipo_consulta' => 'CONSULTA SOB SANÇÃO' ],
            [ 'tx_tipo_consulta' => 'CONSULTA SOB SUBSTITUTIVO' ],
            [ 'tx_tipo_consulta' => 'CONSULTA S/RETIRADA' ],
            [ 'tx_tipo_consulta' => 'CONSULTA /SUGESTÃO' ],
            [ 'tx_tipo_consulta' => 'DESPACHO' ],
            [ 'tx_tipo_consulta' => 'DEVOLVIDO' ],
            [ 'tx_tipo_consulta' => 'E-MAIL' ],
            [ 'tx_tipo_consulta' => 'EMENDA CONSTITUCIONAL' ],
            [ 'tx_tipo_consulta' => 'EMITIR PARECER' ],
            [ 'tx_tipo_consulta' => 'ENCAMINHA ALTERAÇOES' ],
            [ 'tx_tipo_consulta' => 'ENCAMINHA PARA CONHECIMENTO E PROVIDENCIAS' ],
            [ 'tx_tipo_consulta' => 'ENC. DESTAQUES' ],
            [ 'tx_tipo_consulta' => 'ENC. EMENDAS' ],
            [ 'tx_tipo_consulta' => 'ENC. PARECER' ],
            [ 'tx_tipo_consulta' => 'ENC. P/CONHECIMENTO' ],
            [ 'tx_tipo_consulta' => 'ENC. PROPOSIÇÃO' ],
            [ 'tx_tipo_consulta' => 'ENC. RELATÓRIO' ],
            [ 'tx_tipo_consulta' => 'FAVORAVEL AO PLC' ],
            [ 'tx_tipo_consulta' => 'FAVORAVEL AO SUBSTITUTIVO SOB CONDIÇOES' ],
            [ 'tx_tipo_consulta' => 'MEMORANDO' ],
            [ 'tx_tipo_consulta' => 'NAO VISLUMBRO OBICES' ],
            [ 'tx_tipo_consulta' => 'NOTA' ],
            [ 'tx_tipo_consulta' => 'NOTA TÉCNICA' ],
            [ 'tx_tipo_consulta' => 'OBSERVAÇOES' ],
            [ 'tx_tipo_consulta' => 'OFÍCIO' ],
            [ 'tx_tipo_consulta' => 'PARA CONHECIMENTO E PROVIDENCIAS' ],
            [ 'tx_tipo_consulta' => 'PARA SUGESTAO COM SUBSTITUTIVO' ],
            [ 'tx_tipo_consulta' => 'PARECER' ],
            [ 'tx_tipo_consulta' => 'PARECER COM EMENDA' ],
            [ 'tx_tipo_consulta' => 'PARECER COM SUBSTITUTIVO' ],
            [ 'tx_tipo_consulta' => 'PARECER S/SANÇÃO' ],
            [ 'tx_tipo_consulta' => 'P/CONHECIMENTO' ],
            [ 'tx_tipo_consulta' => 'PGFN' ],
            [ 'tx_tipo_consulta' => 'POR SUGESTAO' ],
            [ 'tx_tipo_consulta' => 'RAT. C/PROPOSTAS' ],
            [ 'tx_tipo_consulta' => 'RAT.C/TEXTO CD E EMENDAS' ],
            [ 'tx_tipo_consulta' => 'RATIF. C/EMENDAS' ],
            [ 'tx_tipo_consulta' => 'RATIF. C/PARECER' ],
            [ 'tx_tipo_consulta' => 'RATIF. C/SUBSTITUTIVO' ],
            [ 'tx_tipo_consulta' => 'RATIF. C/TXT.APROV.CD' ],
            [ 'tx_tipo_consulta' => 'RATIFICAÇÃO' ],
            [ 'tx_tipo_consulta' => 'RATIFICA C/ APENSADO' ],
            [ 'tx_tipo_consulta' => 'RATIFICA C/MINUTA' ],
            [ 'tx_tipo_consulta' => 'RATIFICA,CONSIDERANDO A POIÇAO S/DIVERSOS' ],
            [ 'tx_tipo_consulta' => 'RATIFICAR' ],
            [ 'tx_tipo_consulta' => 'RATIFICAR CONSIDERANDO O EXTO APROVADO NA CD' ],
            [ 'tx_tipo_consulta' => 'RATIFICAR CONSIDERANDO O SUBSTITUTIVO DO SF' ],
            [ 'tx_tipo_consulta' => 'RATIFICAR CONSIDERANDO O SUBSTITUTIVO E EMENDA' ],
            [ 'tx_tipo_consulta' => 'RATIFICAR CONSIDERANDO O TEXTO APROVADO NO SF' ],
            [ 'tx_tipo_consulta' => 'RATIFICAR CONSIDERANDO TEXTO ORIGINAL' ],
            [ 'tx_tipo_consulta' => 'RATIFICAR CONSIDERNADO SUGESTAO' ],
            [ 'tx_tipo_consulta' => 'RATIF. S/RETIRADA' ],
            [ 'tx_tipo_consulta' => 'REDAÇÃO FINAL' ],
            [ 'tx_tipo_consulta' => 'REITAR CONSIDERANDO AS EMENDAS' ],
            [ 'tx_tipo_consulta' => 'REIT. C/PARECER' ],
            [ 'tx_tipo_consulta' => 'REIT. C/SUBST. E EMEN.' ],
            [ 'tx_tipo_consulta' => 'REIT. C/SUBSTITUTIVO' ],
            [ 'tx_tipo_consulta' => 'REIT. C/SUGESTÕES' ],
            [ 'tx_tipo_consulta' => 'REITERA' ],
            [ 'tx_tipo_consulta' => 'REITERAÇÃO' ],
            [ 'tx_tipo_consulta' => 'REITERA C/OBSERVAçãO' ],
            [ 'tx_tipo_consulta' => 'REITERA C/PARECER RFB' ],
            [ 'tx_tipo_consulta' => 'REITERA C/SUBS. CAE' ],
            [ 'tx_tipo_consulta' => 'REITERA C/TC LEI RP' ],
            [ 'tx_tipo_consulta' => 'REITERAR' ],
            [ 'tx_tipo_consulta' => 'REITERAR COM URGENCIA' ],
            [ 'tx_tipo_consulta' => 'REITERAR CONSIDERANDO DOCUMENTO ANEXO' ],
            [ 'tx_tipo_consulta' => 'REITERAR CONSIDERANDO EMENDAS E SUBSTITUTIVO' ],
            [ 'tx_tipo_consulta' => 'REITERAR CONSIDERANDO O TEXTO APROVADO NA CD' ],
            [ 'tx_tipo_consulta' => 'REITERAR CONSIDERANDO O TEXTO APROVOVADO NO SF' ],
            [ 'tx_tipo_consulta' => 'REIT. S/RETIRADA' ],
            [ 'tx_tipo_consulta' => 'SANÇAO' ],
            [ 'tx_tipo_consulta' => 'SOLICITA EM' ],
            [ 'tx_tipo_consulta' => 'SOLICITA MANIFESTAÇAO' ],
            [ 'tx_tipo_consulta' => 'SOLICITA MANIFESTAÇÃO' ],
            [ 'tx_tipo_consulta' => 'SOLICITA PARECER' ],
            [ 'tx_tipo_consulta' => 'SUBMETE PARECER' ],
            [ 'tx_tipo_consulta' => 'SUGERE ALTERAÇÕES' ],
            [ 'tx_tipo_consulta' => 'TEXTO APROVADO NA CFT' ]
        ];

        foreach ($tipos_consulta as $tipo_consulta) {
            $this->tipoConsultaRepository->firstOrCreate($tipo_consulta);
        }

        $tipos_posicao = [
            [ 'tx_tipo_posicao' => 'A PROFERIR' ],
            [ 'tx_tipo_posicao' => 'ADEQUAÇAO FINANCEIRA E ORÇAMENTARIA' ],
            [ 'tx_tipo_posicao' => 'ADEQUAÇAO FINANCEIRA E ORÇAMENTARIA COM EMENDAS' ],
            [ 'tx_tipo_posicao' => 'ADEQUAÇAO FINANCEIRA E ORÇAMENTARIA COM SUBSTUTIVO' ],
            [ 'tx_tipo_posicao' => 'ADIADO' ],
            [ 'tx_tipo_posicao' => 'ADITAMENTO' ],
            [ 'tx_tipo_posicao' => 'ADMISSIBILIDADE' ],
            [ 'tx_tipo_posicao' => 'ADMISSIBILIDADE COM EMENDAS' ],
            [ 'tx_tipo_posicao' => 'ADMISSIBILIDADE COM SUBSTITUTIVO' ],
            [ 'tx_tipo_posicao' => 'AGUARDANDO' ],
            [ 'tx_tipo_posicao' => 'AGUARDANDO DESPACHO' ],
            [ 'tx_tipo_posicao' => 'AGUARDANDO REDAÇAO FINAL' ],
            [ 'tx_tipo_posicao' => 'AGUARDAR' ],
            [ 'tx_tipo_posicao' => 'ALTERAÇAO' ],
            [ 'tx_tipo_posicao' => 'ALTERAÇAO COM SUBSTITUTIVO' ],
            [ 'tx_tipo_posicao' => 'ALTERAÇOES' ],
            [ 'tx_tipo_posicao' => 'APENSADO' ],
            [ 'tx_tipo_posicao' => 'APRESENTAÇAO DE RECURSO' ],
            [ 'tx_tipo_posicao' => 'APRESENTAÇAO SUBSTITUTIVO' ],
            [ 'tx_tipo_posicao' => 'APRESENTADA REDAÇAO FINAL' ],
            [ 'tx_tipo_posicao' => 'APROVAÇAO' ],
            [ 'tx_tipo_posicao' => 'APROVAÇAO APENSADO' ],
            [ 'tx_tipo_posicao' => 'APROVAÇAO APENSADO COM EMENDA' ],
            [ 'tx_tipo_posicao' => 'APROVAÇAO COM ALTERAÇOES' ],
            [ 'tx_tipo_posicao' => 'APROVAÇAO COM EMENDA' ],
            [ 'tx_tipo_posicao' => 'APROVAÇAO COM EMENDAS' ],
            [ 'tx_tipo_posicao' => 'APROVAÇAO COM SUBSTITUTIVO' ],
            [ 'tx_tipo_posicao' => 'APROVAÇAO COM SUBSTITUTIVO E EMENDA' ],
            [ 'tx_tipo_posicao' => 'APROVAÇAO DA REDAÇAO FINAL' ],
            [ 'tx_tipo_posicao' => 'APROVAÇAO DO APENSADO COM EMENDAS' ],
            [ 'tx_tipo_posicao' => 'APROVAÇAO DO APENSADO COM SUBEMENDAS' ],
            [ 'tx_tipo_posicao' => 'APROVAÇAO DO TEXTO APROVADO NA CD' ],
            [ 'tx_tipo_posicao' => 'APROVAÇAO DO TEXTO APROVADO NO SF' ],
            [ 'tx_tipo_posicao' => 'APROVAÇAO DO TEXTO ORIGINAL' ],
            [ 'tx_tipo_posicao' => 'APROVAÇAO EMENDAS' ],
            [ 'tx_tipo_posicao' => 'APROVAÇAO SUBSTITUTIVO' ],
            [ 'tx_tipo_posicao' => 'APROVADA REDAÇAO FINAL' ],
            [ 'tx_tipo_posicao' => 'APROVADO' ],
            [ 'tx_tipo_posicao' => 'APROVADO C/EMENDAS' ],
            [ 'tx_tipo_posicao' => 'APROVADO COM ALTERAÇOES' ],
            [ 'tx_tipo_posicao' => 'APROVADO COM COMPLEMENTAÇAO' ],
            [ 'tx_tipo_posicao' => 'APROVADO COM EMENDA' ],
            [ 'tx_tipo_posicao' => 'APROVADO COM SUBSTITUTIVO' ],
            [ 'tx_tipo_posicao' => 'APROVADO COM SUBSTITUTIVO E EMENDA' ],
            [ 'tx_tipo_posicao' => 'APROVADO EMENDAS' ],
            [ 'tx_tipo_posicao' => 'APROVADO O APENSADO' ],
            [ 'tx_tipo_posicao' => 'APROVADO O APENSADO COM EMENDAS' ],
            [ 'tx_tipo_posicao' => 'APROVADO O APENSADO COM SUBEMENDA' ],
            [ 'tx_tipo_posicao' => 'APROVADO O APENSADO COM SUBSTITUTIVO' ],
            [ 'tx_tipo_posicao' => 'APROVADO O SUBSTITUTIVO' ],
            [ 'tx_tipo_posicao' => 'APROVADO TEXTO ORIGINAL' ],
            [ 'tx_tipo_posicao' => 'ARQUIVADO' ],
            [ 'tx_tipo_posicao' => 'ARQUIVAMENTO' ],
            [ 'tx_tipo_posicao' => 'AUDIENCIA NA CCJ' ],
            [ 'tx_tipo_posicao' => 'COMPATIBILIDADE COM EMENDA' ],
            [ 'tx_tipo_posicao' => 'COMPATIBILIDADE E ADEQUAÇAO FINANCEIRA.' ],
            [ 'tx_tipo_posicao' => 'COMPET SRF/PGFN' ],
            [ 'tx_tipo_posicao' => 'COMPET STN/SEAE' ],
            [ 'tx_tipo_posicao' => 'COMPETE A COPAR' ],
            [ 'tx_tipo_posicao' => 'COMPETE A SEREF' ],
            [ 'tx_tipo_posicao' => 'COMPETE BB' ],
            [ 'tx_tipo_posicao' => 'COMPETE BC' ],
            [ 'tx_tipo_posicao' => 'COMPETE CEF' ],
            [ 'tx_tipo_posicao' => 'COMPETE CONFAZ' ],
            [ 'tx_tipo_posicao' => 'COMPETE COTEPE' ],
            [ 'tx_tipo_posicao' => 'COMPETE MEC' ],
            [ 'tx_tipo_posicao' => 'COMPETE MJ' ],
            [ 'tx_tipo_posicao' => 'COMPETE MPOG' ],
            [ 'tx_tipo_posicao' => 'COMPETE MTE' ],
            [ 'tx_tipo_posicao' => 'COMPETE OUTRO MINISTERIO' ],
            [ 'tx_tipo_posicao' => 'COMPETE PGFN' ],
            [ 'tx_tipo_posicao' => 'COMPETE SEAE' ],
            [ 'tx_tipo_posicao' => 'COMPETE SFC' ],
            [ 'tx_tipo_posicao' => 'COMPETE SPE' ],
            [ 'tx_tipo_posicao' => 'COMPETE SPE/SRF' ],
            [ 'tx_tipo_posicao' => 'COMPETE SRF' ],
            [ 'tx_tipo_posicao' => 'COMPETE SRF/SE' ],
            [ 'tx_tipo_posicao' => 'COMPETE STN' ],
            [ 'tx_tipo_posicao' => 'COMPETE STN/SRF' ],
            [ 'tx_tipo_posicao' => 'COMPETE SUSEP' ],
            [ 'tx_tipo_posicao' => 'COMPETENCIA DE OUTRO MINISTERIO' ],
            [ 'tx_tipo_posicao' => 'COMPETENCIA DE OUTRO ORGAO' ],
            [ 'tx_tipo_posicao' => 'CONFIDENCIAL' ],
            [ 'tx_tipo_posicao' => 'CONSIDERAÇOES' ],
            [ 'tx_tipo_posicao' => 'CONSTITUCIONAL' ],
            [ 'tx_tipo_posicao' => 'CONSTITUCIONALIDADE' ],
            [ 'tx_tipo_posicao' => 'CONSTITUCIONALIDADE COM EMENDAS' ],
            [ 'tx_tipo_posicao' => 'CONSTITUCIONALIDADE COM OBSERVAÇOES' ],
            [ 'tx_tipo_posicao' => 'CONSTITUCIONALIDADE COM RESSALVAS' ],
            [ 'tx_tipo_posicao' => 'CONSTITUCIONALIDADE COM SUBSTITUTIVO' ],
            [ 'tx_tipo_posicao' => 'CONSULTA CONSIDERANDO SUBSTITUTIVO E EMENDAS DE PLENÁRIO' ],
            [ 'tx_tipo_posicao' => 'CONT SUBST SENADO FEDERAL' ],
            [ 'tx_tipo_posicao' => 'CONT. SUBST. AO PL' ],
            [ 'tx_tipo_posicao' => 'CONTARIA AO PL AO SUBSTITUTIVO DA CTASP' ],
            [ 'tx_tipo_posicao' => 'CONTARIA AO PL E AO SUBSTITUTIVO DA CCJC' ],
            [ 'tx_tipo_posicao' => 'CONTARIA AO PL E AO SUBSTITUTIVO DA CDC' ],
            [ 'tx_tipo_posicao' => 'CONTARIA AO PL E AO SUBSTITUTIVO DA CREDN' ],
            [ 'tx_tipo_posicao' => 'CONTARIA AO PL E AS EMENDAS' ],
            [ 'tx_tipo_posicao' => 'CONTARIA AO PL E AS EMENDAS DA CAPADR' ],
            [ 'tx_tipo_posicao' => 'CONTARIA AO PL E AS EMENDAS DA CTASP' ],
            [ 'tx_tipo_posicao' => 'CONTARIA AO PLP E AO SUBSTITUTIVO' ],
            [ 'tx_tipo_posicao' => 'CONTARIA AO SUBSTITUTIVO E AO PL' ],
            [ 'tx_tipo_posicao' => 'CONTR. PL E SUBST.' ],
            [ 'tx_tipo_posicao' => 'CONTR. PL E SUBSTITUTIVO' ],
            [ 'tx_tipo_posicao' => 'CONTR. PLS E EMENDAS' ],
            [ 'tx_tipo_posicao' => 'CONTRÁRIA' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA A APROVAÇAO DO PROJETO' ],
            [ 'tx_tipo_posicao' => 'CONTRÁRIA A EMENDA' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA A PEC E AO SUBSTITUTIVO' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA A PEC E SUBSTITUTIVO' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA A PECS E AS EMENDAS DA CCJC' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA A PECS E EMENDAS' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA A PROPOSTA DO MDIC' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO PL AO SUBSTITUTIVO E EMENDAS' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO PL E A EMENDA DA CCJC' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO PL E AO APENSADO' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO PL E AO PLC' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO PL E AO SUBISTITUTIVO DA CFT' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO PL E AO SUBSTITUTIVO' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO PL E AO SUBSTITUTIVO DA CAE' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO PL E AO SUBSTITUTIVO DA CAPADR' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO PL E AO SUBSTITUTIVO DA CDC' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO PL E AO SUBSTITUTIVO DA CDHLP' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO PL E AO SUBSTITUTIVO DA CE' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO PL E AO SUBSTITUTIVO DA CEC' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO PL E AO SUBSTITUTIVO DA CEDEIC' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO PL E AO SUBSTITUTIVO DA COMISAO ESPECIAL' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO PL E AO SUBSTITUTIVO DA CSSF' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO PL E AO SUBSTITUTIVO DA CVT' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO PL E AO SUBSTITUTIVO E EMENDA' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO PL E AO SUBTITUTIVO DO SENADO' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO PL E APENSADO' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO PL E AS EMENDAS DA CAE' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO PL E AS EMENDAS DA CAS' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO PL E AS EMENDAS DA CMADS' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO PL E AS EMENDAS DA CMADS E CDEIC' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO PL E AS EMENDAS DA CSSF' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO PL E EMENDA' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO PL E EMENDAS' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO PL E EMENDAS APRESENTADAS' ],
            [ 'tx_tipo_posicao' => 'CONTRÁRIA AO PL E FAVORÁVEL À EMENDA' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO PL E FAVORAVEL A SUBEMENDA' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO PL E FAVORAVEL AO APENSADO' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO PL E FAVORAVEL AO SUBSTITUTIVO' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO PL E NADA A OPOR AO SUBSTITUTIVO' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO PL E SUBEMENDA' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO PL E SUBSTITUTIVO' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO PL SOB CONDIÇAO' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO PLC' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO PLC E AS EMENDAS' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO PLP E A EMENDA DA CFFC' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO PLP E A EMENDA DA CFT' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO PLP E AO SUBSTITUTIVO' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO PLP E AO SUBSTITUTIVO DA CTASP' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO PLP E AOS APENSADOS' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO PLP E APENSADOS' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO PLS E A EMENDA DA CAE' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO PLS E A EMENDA DA CCJC' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO PLS E AO SUBSTITUTIVO' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO PLS E AO SUBSTITUTIVO COM SUGESTAO' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO PLS E AO SUBSTITUTIVO DA CAE' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO PLS E AO SUBSTITUTIVO DA CCJC' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO PLS E AO SUBSTITUTIVO DA CDR' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO PLS E AS EMENDAS' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO PLS E EMENDAS' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO PLS E FAVORAVEL A EMENDA' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO PLS E FAVORAVEL AS EMENDAS AO SUBSTITUTIVO' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO PLS E SUBSTITUTIVO' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO SUBST. E FAV. AO PL ORIGINAL' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO SUBST. E FAVORAVEL AO PROJETO' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO SUBSTITUTIVO' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO SUBSTITUTIVO CE' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO SUBSTITUTIVO DA CAE' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO SUBSTITUTIVO DA CCJC' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO SUBSTITUTIVO DA CDC' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO SUBSTITUTIVO DA CDEIC' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO SUBSTITUTIVO DA CFT' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO SUBSTITUTIVO DA COMISSAO ESPECIAL' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO SUBSTITUTIVO DA CTASP' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO SUBSTITUTIVO E AO PLC' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO SUBSTITUTIVO E APENSADOS' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AO SUBSTITUTIVO E FAVORAVEL AO PROJETO' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AS ALTERAÇOES' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AS EMENDAS' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AS EMENDAS APRESENTADAS' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA AS EMENDAS DO SENADO' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA COM ALTERAÇOES' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA COM OBSERVAÇOES' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA COM OBSERVAÇÕES' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA COM RESSALVAS' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA COM SUBSTITUTIVO' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA COM SUGESTOES' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA COM SUGESTÕES' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA EM PARTE' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA EM TERMOS AO SUBSTITUTIVO' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA PL E SUBSTITUTIVO' ],
            [ 'tx_tipo_posicao' => 'CONTRARIA PLS E FAVORAVEL A EMENDA E SUBSTITUTIVO' ],
            [ 'tx_tipo_posicao' => 'CONTRÁRIO A SUBEMENDA SUBSTITUTIVA GLOBAL' ],
            [ 'tx_tipo_posicao' => 'CONTRÁRIO AO PARECER' ],
            [ 'tx_tipo_posicao' => 'CONTRÁRIO AO PL' ],
            [ 'tx_tipo_posicao' => 'CONTRÁRIO AO PL E AO SUBSTITUTIVO COM SUGESTÕES' ],
            [ 'tx_tipo_posicao' => 'CONTRáRIO AO PL E EMENDAS' ],
            [ 'tx_tipo_posicao' => 'CONTRÁRIO AO PLS' ],
            [ 'tx_tipo_posicao' => 'CONTRÁRIO AO SUBSTITUTIVO' ],
            [ 'tx_tipo_posicao' => 'CONTRáRIO AO SUBSTITUTIVO COM SUGESTõES' ],
            [ 'tx_tipo_posicao' => 'CONTRáRIO AO SUBSTITUVIVO COM SUGESTõES' ],
            [ 'tx_tipo_posicao' => 'CONTRÁRIO ÀS EMENDAS EM PARTE' ],
            [ 'tx_tipo_posicao' => 'CONTRATIA AOS TEXTOS APROVADOS NA CTASP/CFT/CCJC' ],
            [ 'tx_tipo_posicao' => 'CONTRIA AO PL E EMENDAS' ],
            [ 'tx_tipo_posicao' => 'DESIGNA RELATOR' ],
            [ 'tx_tipo_posicao' => 'DESNECESSÁRIO' ],
            [ 'tx_tipo_posicao' => 'DEVOLVIDO' ],
            [ 'tx_tipo_posicao' => 'DEVOLVIDO.PROJ APROV CD' ],
            [ 'tx_tipo_posicao' => 'EM ESTUDO' ],
            [ 'tx_tipo_posicao' => 'EM EXAME' ],
            [ 'tx_tipo_posicao' => 'EMENDA' ],
            [ 'tx_tipo_posicao' => 'EMENDA CONSTITUCIONAL' ],
            [ 'tx_tipo_posicao' => 'EMENDA PLENÁRIO' ],
            [ 'tx_tipo_posicao' => 'ENC P/OUTRO ÓRGÃO' ],
            [ 'tx_tipo_posicao' => 'ENC P/SEAE' ],
            [ 'tx_tipo_posicao' => 'ENC P/SPE' ],
            [ 'tx_tipo_posicao' => 'ENC P/STN' ],
            [ 'tx_tipo_posicao' => 'ENCAMINHE-SE PARA SEAE' ],
            [ 'tx_tipo_posicao' => 'ESCLARECIMENTOS' ],
            [ 'tx_tipo_posicao' => 'FAV. AO PLS E SUBST.' ],
            [ 'tx_tipo_posicao' => 'FAV. AO SUBSTITUTIVO' ],
            [ 'tx_tipo_posicao' => 'FAV. APENS. C/ALT.' ],
            [ 'tx_tipo_posicao' => 'FAV. APENS. C/EMENDAS' ],
            [ 'tx_tipo_posicao' => 'FAV. APENS. C/SUBST.' ],
            [ 'tx_tipo_posicao' => 'FAV. APENSADO' ],
            [ 'tx_tipo_posicao' => 'FAV. C/ALTERAÇÕES' ],
            [ 'tx_tipo_posicao' => 'FAV. C/EMENDAS' ],
            [ 'tx_tipo_posicao' => 'FAV. C/OBSERVAÇÕES' ],
            [ 'tx_tipo_posicao' => 'FAV. C/RECOMENDAÇÕES' ],
            [ 'tx_tipo_posicao' => 'FAV. C/RESSALVAS' ],
            [ 'tx_tipo_posicao' => 'FAV. C/RESTRIÇÕES' ],
            [ 'tx_tipo_posicao' => 'FAV. C/SUBEMENDAS' ],
            [ 'tx_tipo_posicao' => 'FAV. C/SUBSTITUTIVO' ],
            [ 'tx_tipo_posicao' => 'FAV. C/SUGESTÃO/RESSALVAS' ],
            [ 'tx_tipo_posicao' => 'FAV. C/SUGESTÕES' ],
            [ 'tx_tipo_posicao' => 'FAV. EM PARTE' ],
            [ 'tx_tipo_posicao' => 'FAV. EM PARTE AO SUBST.' ],
            [ 'tx_tipo_posicao' => 'FAV. EMENDAS' ],
            [ 'tx_tipo_posicao' => 'FAV. EMENDAS C/ALT.' ],
            [ 'tx_tipo_posicao' => 'FAV. PL CONTR. SUBST.' ],
            [ 'tx_tipo_posicao' => 'FAV. PL E APENS.' ],
            [ 'tx_tipo_posicao' => 'FAV. PL E CONTR APENSADO' ],
            [ 'tx_tipo_posicao' => 'FAV. PL E EMENDAS' ],
            [ 'tx_tipo_posicao' => 'FAV. PL E SUBST.' ],
            [ 'tx_tipo_posicao' => 'FAV. SOB CONDIÇÕES' ],
            [ 'tx_tipo_posicao' => 'FAV. SUBST DA CSSF' ],
            [ 'tx_tipo_posicao' => 'FAV. SUBST. C/ALT.' ],
            [ 'tx_tipo_posicao' => 'FAV. SUBST. C/EMENDAS' ],
            [ 'tx_tipo_posicao' => 'FAV. SUBST. C/SUG.' ],
            [ 'tx_tipo_posicao' => 'FAV. SUBSTITUTIVO' ],
            [ 'tx_tipo_posicao' => 'FAV. TEXTO ORIGINAL' ],
            [ 'tx_tipo_posicao' => 'FAV. TXT APROV. CD' ],
            [ 'tx_tipo_posicao' => 'FAV. TXT APROV. SF' ],
            [ 'tx_tipo_posicao' => 'FAV.AO SUBST. C/RESSALVA' ],
            [ 'tx_tipo_posicao' => 'FAV.AO SUBST.DO SENADO' ],
            [ 'tx_tipo_posicao' => 'FAV.SUBST.C/RESSALVA' ],
            [ 'tx_tipo_posicao' => 'FAVORÁVEL' ],
            [ 'tx_tipo_posicao' => 'FAVORAVEL A EMENDA E AO SUBSTITUTIVO Nº1 DA CCT' ],
            [ 'tx_tipo_posicao' => 'FAVORAVEL AO PL CONTRARIA AS EMENDAS' ],
            [ 'tx_tipo_posicao' => 'FAVORáVEL AO PL E AO SUBSTITUTIVO' ],
            [ 'tx_tipo_posicao' => 'FAVORáVEL AO PL E AO SUBSTITUTIVO COM SUGESTõES' ],
            [ 'tx_tipo_posicao' => 'FAVORAVEL AO PL E CONTRARIA A EMENDA DA CTASP' ],
            [ 'tx_tipo_posicao' => 'FAVORAVEL AO PL E CONTRARIA AO SUBSTITUTIVO' ],
            [ 'tx_tipo_posicao' => 'FAVORAVEL AO PL E CONTRARIA AS EMENDAS' ],
            [ 'tx_tipo_posicao' => 'FAVORÁVEL AO PL E EMENDAS COM SUGESTÕES' ],
            [ 'tx_tipo_posicao' => 'FAVORÁVEL AO PL E SUBSTITUTIVO COM RECOMENDAÇÕES' ],
            [ 'tx_tipo_posicao' => 'FAVORAVEL AO PL SOB CONDIÇOES E CONTRARIA AO SUBSTITUTIVO' ],
            [ 'tx_tipo_posicao' => 'FAVORAVEL AO PLC' ],
            [ 'tx_tipo_posicao' => 'FAVORAVEL AO PLC COM ALTERAÇÕES' ],
            [ 'tx_tipo_posicao' => 'FAVORáVEL AO PLC E CONTRáRIO àS EMENDAS' ],
            [ 'tx_tipo_posicao' => 'FAVORAVEL AO PLC E CONTRARIO AS EMENDAS DO SENADO' ],
            [ 'tx_tipo_posicao' => 'FAVORAVEL AO PLP E A EMENDA DA CEDEIC' ],
            [ 'tx_tipo_posicao' => 'FAVORÁVEL AO PLP E CONTRARIA AO SUBSTITUTIVO' ],
            [ 'tx_tipo_posicao' => 'FAVORAVEL AO PLS E AO SUBSTITUTIVO' ],
            [ 'tx_tipo_posicao' => 'FAVORAVEL AO PLS E SUBSTITUTIVO' ],
            [ 'tx_tipo_posicao' => 'FAVORáVEL AO PRS E CONTRáRIO à EMENDA' ],
            [ 'tx_tipo_posicao' => 'FAVORÁVEL AO SUBSTITUTIVO' ],
            [ 'tx_tipo_posicao' => 'FAVORAVEL AO SUBSTITUTIVO COM ALTERAÇOES' ],
            [ 'tx_tipo_posicao' => 'FAVORAVEL AO SUBSTITUTIVO COM SUGESTOES' ],
            [ 'tx_tipo_posicao' => 'FAVORAVEL AO SUBSTITUTIVO DA CVM' ],
            [ 'tx_tipo_posicao' => 'FAVORáVEL AO SUBSTITUTIVO E CONTRáRIO àS EMENDAS' ],
            [ 'tx_tipo_posicao' => 'FAVORAVEL AO SUBSTITUTIVO S0B CONDIÇÕES' ],
            [ 'tx_tipo_posicao' => 'FAVORAVEL AO TEXTO APRESENTADO PELA CAMARA' ],
            [ 'tx_tipo_posicao' => 'FAVORAVEL AO TEXTO APRESENTADO PELO SENADO' ],
            [ 'tx_tipo_posicao' => 'FAVORAVEL AO TEXTO DO EXECUTIVO' ],
            [ 'tx_tipo_posicao' => 'FAVORAVEL AO TEXTO ORIGINAL' ],
            [ 'tx_tipo_posicao' => 'FAVORAVEL AS EMENDAS DA CE SOB CONDIÇOES' ],
            [ 'tx_tipo_posicao' => 'FAVORÁVEL C/ALTERAÇÃO' ],
            [ 'tx_tipo_posicao' => 'FAVORÁVEL C/EMENDA' ],
            [ 'tx_tipo_posicao' => 'FAVORÁVEL C/EMENDAS' ],
            [ 'tx_tipo_posicao' => 'FAVORAVEL COM OBSERVAÇOES' ],
            [ 'tx_tipo_posicao' => 'FAVORAVEL COM RESSALVAS' ],
            [ 'tx_tipo_posicao' => 'FAVORAVEL COM SUGESTOES/RESSALVAS' ],
            [ 'tx_tipo_posicao' => 'FAVORAVEL SOB CONDIÇOES AO SUBSTITUTIVO DA CDC' ],
            [ 'tx_tipo_posicao' => 'FAVORAVEL SOB CONDIÇOES AO SUBSTITUTIVO DA CEC' ],
            [ 'tx_tipo_posicao' => 'FAVORAVEL SOB CONDIÇOES AO SUBSTITUTIVO DA CTASP' ],
            [ 'tx_tipo_posicao' => 'INADEQUAÇAO FINANCEIRA E ORÇAMENTARIA' ],
            [ 'tx_tipo_posicao' => 'INADMISSIBILIDADE' ],
            [ 'tx_tipo_posicao' => 'INCONST. C/OBS.' ],
            [ 'tx_tipo_posicao' => 'INCONSTITUCIONAL' ],
            [ 'tx_tipo_posicao' => 'INCONSTITUCIONALIDADE' ],
            [ 'tx_tipo_posicao' => 'INDIF. CONS. EMENDAS' ],
            [ 'tx_tipo_posicao' => 'INDIF. CONS. SUBST.' ],
            [ 'tx_tipo_posicao' => 'INDIFERENTE' ],
            [ 'tx_tipo_posicao' => 'INJURIDICIDADE' ],
            [ 'tx_tipo_posicao' => 'INOPORTUNO' ],
            [ 'tx_tipo_posicao' => 'LEI' ],
            [ 'tx_tipo_posicao' => 'MANTER' ],
            [ 'tx_tipo_posicao' => 'MANTER C/ALTERAÇÕES' ],
            [ 'tx_tipo_posicao' => 'MANTER C/RESTRIÇÕES' ],
            [ 'tx_tipo_posicao' => 'MATÉRIA PREJUDICADA' ],
            [ 'tx_tipo_posicao' => 'NADA A OPOR' ],
            [ 'tx_tipo_posicao' => 'NADA A OPOR AO PL E AO SUBSTITUTIVO' ],
            [ 'tx_tipo_posicao' => 'NADA A OPOR AO PL E AO SUBSTITUTIVO COM OBSERVAÇÕES' ],
            [ 'tx_tipo_posicao' => 'NADA A OPOR AO PL E CONTRáRIO àS EMENDAS' ],
            [ 'tx_tipo_posicao' => 'NADA A OPOR AO PL E EMENDAS' ],
            [ 'tx_tipo_posicao' => 'NADA A OPOR AO SUBST CCJC' ],
            [ 'tx_tipo_posicao' => 'NADA A OPOR AO SUBSTITUTIVO' ],
            [ 'tx_tipo_posicao' => 'NADA A OPOR ÀS EMENDAS' ],
            [ 'tx_tipo_posicao' => 'NADA A OPOR COM OBSERVAÇAO' ],
            [ 'tx_tipo_posicao' => 'NADA A OPOR COM OBSERVAçõES' ],
            [ 'tx_tipo_posicao' => 'NADA A OPOR COM RESSALVAS' ],
            [ 'tx_tipo_posicao' => 'NADA A OPOR PL EMEN CTASP' ],
            [ 'tx_tipo_posicao' => 'NADA A OPOR SUBST CSPCCO' ],
            [ 'tx_tipo_posicao' => 'NADA OPOR AO SUBS DA CFT' ],
            [ 'tx_tipo_posicao' => 'NADA OPOR AO SUBSTITUTIVO' ],
            [ 'tx_tipo_posicao' => 'NADA OPOR ÀS EMENDAS' ],
            [ 'tx_tipo_posicao' => 'NADA OPOR C/ALTERAÇÕES' ],
            [ 'tx_tipo_posicao' => 'NADA OPOR C/OBSERVAÇÕES' ],
            [ 'tx_tipo_posicao' => 'NADA OPOR C/SUG.' ],
            [ 'tx_tipo_posicao' => 'NADA OPOR C/SUGESTÕES' ],
            [ 'tx_tipo_posicao' => 'NADA OPOR CONS. EMENDAS' ],
            [ 'tx_tipo_posicao' => 'NADA OPOR CONSIDERANDO O SUBSTITUTIVO' ],
            [ 'tx_tipo_posicao' => 'NADA OPOR EMENDAS' ],
            [ 'tx_tipo_posicao' => 'NADA OPOR SUBST.' ],
            [ 'tx_tipo_posicao' => 'NADA OPOR TXT AP.CD.' ],
            [ 'tx_tipo_posicao' => 'NADA OPOR TXT AP.SF.' ],
            [ 'tx_tipo_posicao' => 'NÃO COMPETE' ],
            [ 'tx_tipo_posicao' => 'NAO COMPETE AO MF' ],
            [ 'tx_tipo_posicao' => 'NÃO COMPETE OPINAR' ],
            [ 'tx_tipo_posicao' => 'NÃO DEFINIDA' ],
            [ 'tx_tipo_posicao' => 'NÃO HÁ IMPACTO FINANCEIRO' ],
            [ 'tx_tipo_posicao' => 'NAO HA IMPACTO FISCAL PARA A UNIAO' ],
            [ 'tx_tipo_posicao' => 'NAO HA IMPACTO ORÇAMENTARIO' ],
            [ 'tx_tipo_posicao' => 'NAO HA INDICE DE INCONSTITUCIONALIDADE' ],
            [ 'tx_tipo_posicao' => 'NÃO HÁ ÓBICE' ],
            [ 'tx_tipo_posicao' => 'NAO HA OBICE SOB CONDIÇAO' ],
            [ 'tx_tipo_posicao' => 'NÃO HÁ ÓBICES AO SUBSTIT.' ],
            [ 'tx_tipo_posicao' => 'NÃO MANIFESTOU' ],
            [ 'tx_tipo_posicao' => 'NÃO OPINOU' ],
            [ 'tx_tipo_posicao' => 'NãO SE OPõE' ],
            [ 'tx_tipo_posicao' => 'NAO SE VISLUMBRA OBICE' ],
            [ 'tx_tipo_posicao' => 'NAO VISLUMBRAMOS OBICES' ],
            [ 'tx_tipo_posicao' => 'NAO VISLUMBRO OBICE' ],
            [ 'tx_tipo_posicao' => 'OBSERVAÇOES' ],
            [ 'tx_tipo_posicao' => 'OBSERVAÇÕES' ],
            [ 'tx_tipo_posicao' => 'OUVIR BC' ],
            [ 'tx_tipo_posicao' => 'OUVIR BC/STN' ],
            [ 'tx_tipo_posicao' => 'OUVIR BNDES' ],
            [ 'tx_tipo_posicao' => 'OUVIR CEF' ],
            [ 'tx_tipo_posicao' => 'OUVIR CVM' ],
            [ 'tx_tipo_posicao' => 'OUVIR CVM/SPE' ],
            [ 'tx_tipo_posicao' => 'OUVIR FAT' ],
            [ 'tx_tipo_posicao' => 'OUVIR IBAMA' ],
            [ 'tx_tipo_posicao' => 'OUVIR INCRA' ],
            [ 'tx_tipo_posicao' => 'OUVIR MA' ],
            [ 'tx_tipo_posicao' => 'OUVIR MAER' ],
            [ 'tx_tipo_posicao' => 'OUVIR MARA' ],
            [ 'tx_tipo_posicao' => 'OUVIR MEC' ],
            [ 'tx_tipo_posicao' => 'OUVIR MINC' ],
            [ 'tx_tipo_posicao' => 'OUVIR MJ' ],
            [ 'tx_tipo_posicao' => 'OUVIR MPAS' ],
            [ 'tx_tipo_posicao' => 'OUVIR MPO' ],
            [ 'tx_tipo_posicao' => 'OUVIR MS' ],
            [ 'tx_tipo_posicao' => 'OUVIR MTB' ],
            [ 'tx_tipo_posicao' => 'OUVIR MTPS' ],
            [ 'tx_tipo_posicao' => 'OUVIR OUTRO ÓRGÃO' ],
            [ 'tx_tipo_posicao' => 'OUVIR OUTROS MINISTÉRIOS' ],
            [ 'tx_tipo_posicao' => 'OUVIR PGFN' ],
            [ 'tx_tipo_posicao' => 'OUVIR SAIN' ],
            [ 'tx_tipo_posicao' => 'OUVIR SE' ],
            [ 'tx_tipo_posicao' => 'OUVIR SEAE' ],
            [ 'tx_tipo_posicao' => 'OUVIR SEREF' ],
            [ 'tx_tipo_posicao' => 'OUVIR SPE' ],
            [ 'tx_tipo_posicao' => 'OUVIR SPE/PGFN' ],
            [ 'tx_tipo_posicao' => 'OUVIR SPU' ],
            [ 'tx_tipo_posicao' => 'OUVIR SRF' ],
            [ 'tx_tipo_posicao' => 'OUVIR SRF/PGFN' ],
            [ 'tx_tipo_posicao' => 'OUVIR SRF/SEAE' ],
            [ 'tx_tipo_posicao' => 'OUVIR SRF/SPE' ],
            [ 'tx_tipo_posicao' => 'OUVIR SRF/STN' ],
            [ 'tx_tipo_posicao' => 'OUVIR STN' ],
            [ 'tx_tipo_posicao' => 'OUVIR STN/MPO' ],
            [ 'tx_tipo_posicao' => 'OUVIR STN/PGFN' ],
            [ 'tx_tipo_posicao' => 'OUVIR SUSEP' ],
            [ 'tx_tipo_posicao' => 'P/INC DA COMIS' ],
            [ 'tx_tipo_posicao' => 'PELA RETIRADA' ],
            [ 'tx_tipo_posicao' => 'PENDENTE' ],
            [ 'tx_tipo_posicao' => 'PERDA DE OBJETO' ],
            [ 'tx_tipo_posicao' => 'PERDA DE OBJETO DO PL' ],
            [ 'tx_tipo_posicao' => 'PGFN' ],
            [ 'tx_tipo_posicao' => 'PIS/PASEP' ],
            [ 'tx_tipo_posicao' => 'PIS/PASEP (COFINS)' ],
            [ 'tx_tipo_posicao' => 'PONDERAÇOES' ],
            [ 'tx_tipo_posicao' => 'PONDERAÇÕES' ],
            [ 'tx_tipo_posicao' => 'PR/PARECER' ],
            [ 'tx_tipo_posicao' => 'PREJUDICADO' ],
            [ 'tx_tipo_posicao' => 'PREJUDICADO P/LEI' ],
            [ 'tx_tipo_posicao' => 'PREJUDICIALIDADE' ],
            [ 'tx_tipo_posicao' => 'PRIORIDADE' ],
            [ 'tx_tipo_posicao' => 'PRIORITÁRIO' ],
            [ 'tx_tipo_posicao' => 'PROPÕE ALTERAÇÕES' ],
            [ 'tx_tipo_posicao' => 'PROPOE ALTERAR TEXTO' ],
            [ 'tx_tipo_posicao' => 'PROPÕE ARQUIVAMENTO' ],
            [ 'tx_tipo_posicao' => 'PROPÕE DECRETO' ],
            [ 'tx_tipo_posicao' => 'PROPOE RETIRADA' ],
            [ 'tx_tipo_posicao' => 'PROPÕE VETO' ],
            [ 'tx_tipo_posicao' => 'PRORROGAÇÃO' ],
            [ 'tx_tipo_posicao' => 'PROSPERAR' ],
            [ 'tx_tipo_posicao' => 'RATF.P/CONT.EMENDAS' ],
            [ 'tx_tipo_posicao' => 'RATIF. C/EMENDAS' ],
            [ 'tx_tipo_posicao' => 'RATIF. C/OBS.' ],
            [ 'tx_tipo_posicao' => 'RATIF. C/RESSALVAS' ],
            [ 'tx_tipo_posicao' => 'RATIF. C/SUBST.' ],
            [ 'tx_tipo_posicao' => 'RATIF. POS.ANTERIOR' ],
            [ 'tx_tipo_posicao' => 'RATIFICA' ],
            [ 'tx_tipo_posicao' => 'RATIFICA POSIÇAO CONTRARIA' ],
            [ 'tx_tipo_posicao' => 'RATIFICA POSIÇAO FAVORAVEL' ],
            [ 'tx_tipo_posicao' => 'RATIFICAR' ],
            [ 'tx_tipo_posicao' => 'REAUTUAÇÃO DO PROJETO' ],
            [ 'tx_tipo_posicao' => 'REDISTRIBUIDO' ],
            [ 'tx_tipo_posicao' => 'REGULAM. P/LC' ],
            [ 'tx_tipo_posicao' => 'REGULAMENTADO P/MP' ],
            [ 'tx_tipo_posicao' => 'REITERA' ],
            [ 'tx_tipo_posicao' => 'REITERA C/PARECER RFB' ],
            [ 'tx_tipo_posicao' => 'REITERAR' ],
            [ 'tx_tipo_posicao' => 'REJEIÇAO DE ALGUNS ARTIGOS' ],
            [ 'tx_tipo_posicao' => 'REJEIÇAO DO PL APROVAÇAO DO APENSADO' ],
            [ 'tx_tipo_posicao' => 'REJEIÇAO DO PL E EMENDAS' ],
            [ 'tx_tipo_posicao' => 'REJEIÇAO DO PL E SUBSTITUTIVO' ],
            [ 'tx_tipo_posicao' => 'REJEIÇAO PL E APENSADO' ],
            [ 'tx_tipo_posicao' => 'REJEIÇAO PL E APENSADOS' ],
            [ 'tx_tipo_posicao' => 'REJEITADO' ],
            [ 'tx_tipo_posicao' => 'REJEITAR' ],
            [ 'tx_tipo_posicao' => 'RESSALVAS' ],
            [ 'tx_tipo_posicao' => 'RESTITUIÇÃO' ],
            [ 'tx_tipo_posicao' => 'RESTRIÇOES' ],
            [ 'tx_tipo_posicao' => 'RESTRIÇÕES' ],
            [ 'tx_tipo_posicao' => 'RETIRADA' ],
            [ 'tx_tipo_posicao' => 'RETIRADA C/EMENDAS' ],
            [ 'tx_tipo_posicao' => 'RETIRADO' ],
            [ 'tx_tipo_posicao' => 'RETIRAR' ],
            [ 'tx_tipo_posicao' => 'SEM EFICÁCIA' ],
            [ 'tx_tipo_posicao' => 'SEM MANIFESTAÇAO' ],
            [ 'tx_tipo_posicao' => 'SEM PARECER' ],
            [ 'tx_tipo_posicao' => 'SOBRESTAMENTO' ],
            [ 'tx_tipo_posicao' => 'SOLICITA PRAZO' ],
            [ 'tx_tipo_posicao' => 'SUBEMENDA' ],
            [ 'tx_tipo_posicao' => 'SUBSTITUTIVO' ],
            [ 'tx_tipo_posicao' => 'SUG. ALTERAÇÕES' ],
            [ 'tx_tipo_posicao' => 'SUGERE A RETIRADA' ],
            [ 'tx_tipo_posicao' => 'SUGERE ALTERAÇAO' ],
            [ 'tx_tipo_posicao' => 'SUGERE ALTERAÇAO AO SUBSTITUTIVO DA CFT' ],
            [ 'tx_tipo_posicao' => 'SUGERE ALTERAÇAO NO SUBSTITUTIVO' ],
            [ 'tx_tipo_posicao' => 'SUGERE ALTERAÇOES' ],
            [ 'tx_tipo_posicao' => 'SUGERE ARQUIVAMENTO' ],
            [ 'tx_tipo_posicao' => 'SUGERE EMENDAS' ],
            [ 'tx_tipo_posicao' => 'SUGERE JUDICIARIO' ],
            [ 'tx_tipo_posicao' => 'SUGERE NOVA REDAÇAO' ],
            [ 'tx_tipo_posicao' => 'SUGERE OUTRO MINISTERIO' ],
            [ 'tx_tipo_posicao' => 'SUGERE OUTRO ORGÃO' ],
            [ 'tx_tipo_posicao' => 'SUGERE OUTROS MINISTERIOS' ],
            [ 'tx_tipo_posicao' => 'SUGERE SUBSTITUTIVO' ],
            [ 'tx_tipo_posicao' => 'SUGERE VETO' ],
            [ 'tx_tipo_posicao' => 'SUGESTÃO AO SUBSTITUTIVO' ],
            [ 'tx_tipo_posicao' => 'SUGESTOES' ],
            [ 'tx_tipo_posicao' => 'SUGESTÕES' ],
            [ 'tx_tipo_posicao' => 'URGÊNCIA' ],
            [ 'tx_tipo_posicao' => 'VALORES EM MOEDAS' ],
            [ 'tx_tipo_posicao' => 'VER PARECER SPE' ],
            [ 'tx_tipo_posicao' => 'VER PARECER STN' ],
            [ 'tx_tipo_posicao' => 'VETO' ],
            [ 'tx_tipo_posicao' => 'VETO A ARTIGO' ],
            [ 'tx_tipo_posicao' => 'VETO A INCISO' ],
            [ 'tx_tipo_posicao' => 'VETO INTEGRAL' ],
            [ 'tx_tipo_posicao' => 'VETO PARCIAL' ],
            [ 'tx_tipo_posicao' => 'VETO TOTAL' ]
        ];

        foreach ($tipos_posicao as $tipo_posicao) {
            $this->tipoPosicaoRepository->firstOrCreate($tipo_posicao);
        }

        $tipos_situacao = [
            [
               'co_tipo_situacao' => 64,
               'tx_tipo_situacao' => 'TRANSFORMADA EM NORMA JURÍDICA',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'S',
            ],
            [
               'co_tipo_situacao' => 55,
               'tx_tipo_situacao' => 'REMETIDA À PROMULGAÇÃO',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'S',
            ],
            [
               'co_tipo_situacao' => 92,
               'tx_tipo_situacao' => 'TRANSFORMADA EM NORMA JURÍDICA COM VETO PARCIAL',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'S',
            ],
            [
               'co_tipo_situacao' => 101,
               'tx_tipo_situacao' => 'TRANSFORMADA EM PROJ. DE DEC. LEGISLATIVO DO CONGRESSO',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'S',
            ],
            [
               'co_tipo_situacao' => 28,
               'tx_tipo_situacao' => 'ARQUIVADA AO FINAL DA LEGISLATURA',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'E',
            ],
            [
               'co_tipo_situacao' => 179,
               'tx_tipo_situacao' => 'DEVOLVIDO EM ATENDIMENTO A DECISAO JUDICIAL',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'E',
            ],
            [
               'co_tipo_situacao' => 43,
               'tx_tipo_situacao' => 'PREJUDICADA',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'E',
            ],
            [
               'co_tipo_situacao' => 49,
               'tx_tipo_situacao' => 'REJEITADA',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'E',
            ],
            [
               'co_tipo_situacao' => 97,
               'tx_tipo_situacao' => 'REJEITADA A MATÉRIA (DECISÃO TERMINATIVA)',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'E',
            ],
            [
               'co_tipo_situacao' => 60,
               'tx_tipo_situacao' => 'RETIRADA PELO AUTOR',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'E',
            ],
            [
               'co_tipo_situacao' => 63,
               'tx_tipo_situacao' => 'SEM EFICÁCIA',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'E',
            ],
            [
               'co_tipo_situacao' => 77,
               'tx_tipo_situacao' => 'VETADA',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'E',
            ],
            [
               'co_tipo_situacao' => 48,
               'tx_tipo_situacao' => 'REVOGADA',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'E',
            ],
            [
               'co_tipo_situacao' => 87,
               'tx_tipo_situacao' => 'AGUARDANDO DESIGNAÇÃO DO RELATOR',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 11,
               'tx_tipo_situacao' => 'AGUARDANDO INFORMAÇÕES',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 12,
               'tx_tipo_situacao' => 'AGUARDANDO INTERPOSIÇÃO DE RECURSO',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 14,
               'tx_tipo_situacao' => 'AGUARDANDO LEITURA PARECER (ES)',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 167,
               'tx_tipo_situacao' => 'AGUARDANDO PRAZO PARA ELABORAÇÃO DO PDL NA COMISSÃO MISTA',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 168,
               'tx_tipo_situacao' => 'AGUARDANDO PRAZO PARA ELABORAÇÃO DO PDL POR PARLAMENTAR',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 20,
               'tx_tipo_situacao' => 'AGUARDANDO RECEBIMENTO DE EMENDAS',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 156,
               'tx_tipo_situacao' => 'ATENDIMENDO DA ADEQUAÇÃO ORÇAMENTÁRIA E FINANCEIRA',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 158,
               'tx_tipo_situacao' => 'APROVADO O PARECER NA COMISSÃO - PELA APROVAÇÃO DA MEDIDA',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 159,
               'tx_tipo_situacao' => 'APROVADO O PARECER NA COMISSÃO - APROVAÇÃO PARCIAL DA MEDIDA',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 154,
               'tx_tipo_situacao' => 'ATENDIMENTO DOS PRESUPOSTOS CONSTITUCIONAIS',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 163,
               'tx_tipo_situacao' => 'APROVADO O PARECER NA COMISSÃO - PELA APRESENTAÇÃO DE PDL',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 162,
               'tx_tipo_situacao' => 'APROVADO PARECER NA COMISSÃO - PREJUDICIONALIDADE DA MEDID',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 160,
               'tx_tipo_situacao' => 'APROVADO O PARECER NA COMISSÃO - PELA REJEIÇÃO DA MEDIDA',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 173,
               'tx_tipo_situacao' => 'APROVADO PARECER DE ADMISSIBILIDADE',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 174,
               'tx_tipo_situacao' => 'APROVADO PARECER DE PRONÚNCIA',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 89,
               'tx_tipo_situacao' => 'APROVADO PARECER NA COMISSÃO',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 161,
               'tx_tipo_situacao' => 'APROVADO O PARECER NA COMISSÃO - NOS TERMOS DO PLV',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 32,
               'tx_tipo_situacao' => 'COMISSÃO TEMPORÁRIA EXTINTA',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 149,
               'tx_tipo_situacao' => 'DESARQUIVADA - RISF ART 332 § 1º',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 169,
               'tx_tipo_situacao' => 'ENCERRADO O PRAZO PARA ELABORAÇÃO DO PDL NA COMISSÃO MISTA',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 170,
               'tx_tipo_situacao' => 'ENCERRADO O PRAZO PARA ELABORAÇÃO DO PDL POR PARLAMENTAR',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 153,
               'tx_tipo_situacao' => 'ENCERRADO O PRAZO PARA RECEBIMENTO DE EMENDAS',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 151,
               'tx_tipo_situacao' => 'FIXAÇÃO DE CALENDÁRIO',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 78,
               'tx_tipo_situacao' => 'INCLUÍDA EM ORDEM DO DIA',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 127,
               'tx_tipo_situacao' => 'INCLUÍDO PARECER EM ORDEM DO DIA',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 114,
               'tx_tipo_situacao' => 'INCLUÍDO REQUERIMENTO EM ORDEM DO DIA DA SESSÃO DELIBERATIVA',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 105,
               'tx_tipo_situacao' => 'INFORMAÇÕES NEGADAS',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 79,
               'tx_tipo_situacao' => 'INFORMAÇÕES RECEBIDAS',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 138,
               'tx_tipo_situacao' => 'INCLUÍDA NA PAUTA DA REUNIÃO',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 178,
               'tx_tipo_situacao' => 'COMISSÃO INSTALADA',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 147,
               'tx_tipo_situacao' => 'MATÉRIA LIDA EM PLENÁRIO.',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 90,
               'tx_tipo_situacao' => 'PEDIDO DE VISTA CONCEDIDO',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 152,
               'tx_tipo_situacao' => 'PRAZO FINAL PRORROGADO',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 8,
               'tx_tipo_situacao' => 'PRONTO PARA DELIBERAÇÃO DO PLENÁRIO',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 42,
               'tx_tipo_situacao' => 'PRONTA PARA A PAUTA NA COMISSÃO',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 91,
               'tx_tipo_situacao' => 'MATÉRIA COM A RELATORIA',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 66,
               'tx_tipo_situacao' => 'TRANSFORMADA EM PROJETO DECRETO LEGISLATIVO',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 150,
               'tx_tipo_situacao' => 'TRANSFORMADA EM PROPOSTA DE EMENDA CONSTITUCIONAL',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 69,
               'tx_tipo_situacao' => 'TRANSFORMADA EM PROJETO DE RESOLUÇÃO - CN',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 70,
               'tx_tipo_situacao' => 'TRANSFORMADA EM PROJETO DE RESOLUÇÃO DO SENADO',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 166,
               'tx_tipo_situacao' => 'APROVADA A MEDIDA PROVISÓRIA - PREFERÊNCIA SOBRE PLV',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 165,
               'tx_tipo_situacao' => 'APROVADO PROJETO DE LEI DE CONVERSÃO PREFERÊNCIA SOBRE MEDID',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 164,
               'tx_tipo_situacao' => 'APROVADO PROJETO DE LEI DE CONVERSÃO COM ALTERAÇÕES',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 146,
               'tx_tipo_situacao' => 'APRECIADA EM DECISÃO TERMINATIVA PELAS COMISSÕES',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 25,
               'tx_tipo_situacao' => 'APROVADA',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 96,
               'tx_tipo_situacao' => 'APROVADA A MATÉRIA (DECISÃO TERMINATIVA)',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 107,
               'tx_tipo_situacao' => 'CONHECIDA.',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 109,
               'tx_tipo_situacao' => 'DEFERIDA',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 136,
               'tx_tipo_situacao' => 'NÃO ADMISSÃO DOS PRESSUPOSTOS CONSTITUCIONAIS',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 108,
               'tx_tipo_situacao' => 'INDEFERIDA',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 157,
               'tx_tipo_situacao' => 'NÃO ATENDIMENDO DA ADEQUAÇÃO ORÇAMENTÁRIA E FINANCEIRA',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 155,
               'tx_tipo_situacao' => 'NÃO ATENDIMENTO DOS PRESUPOSTOS CONSTITUCIONAIS',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 52,
               'tx_tipo_situacao' => 'REMETIDA À CÂMARA DOS DEPUTADOS',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 57,
               'tx_tipo_situacao' => 'REMETIDA À SANÇÃO',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 59,
               'tx_tipo_situacao' => 'REMETIDA AO TRIBUNAL DE CONTAS DA UNIÃO',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 62,
               'tx_tipo_situacao' => 'SOBRESTADA',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 172,
               'tx_tipo_situacao' => 'SOBRESTANDO A PAUTA DO CONGRESSO NACIONAL',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 171,
               'tx_tipo_situacao' => 'TRANSFORMADA EM PROJETO DE LEI DE CONVERSÃO',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 99,
               'tx_tipo_situacao' => 'TRANSFORMADA EM PROJETO DE LEI DO CONGRESSO',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 67,
               'tx_tipo_situacao' => 'TRANSFORMADA EM PROJETO DE LEI DO SENADO',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 68,
               'tx_tipo_situacao' => 'TRANSFORMADA EM PROJETO DE LEI DE CONVERSÃO',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 141,
               'tx_tipo_situacao' => 'TRAMITAÇÃO INTERROMPIDA',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 103,
               'tx_tipo_situacao' => 'VETO DERRUBADO',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 102,
               'tx_tipo_situacao' => 'VETO MANTIDO',
               'sg_casa_situacao' => 'SF',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 1140,
               'tx_tipo_situacao' => 'Transformado em Norma Jurídica',
               'sg_casa_situacao' => 'CD',
               'sg_status_situacao' => 'S',
            ],
            [
               'co_tipo_situacao' => 923,
               'tx_tipo_situacao' => 'Arquivada',
               'sg_casa_situacao' => 'CD',
               'sg_status_situacao' => 'E',
            ],
            [
               'co_tipo_situacao' => 1120,
               'tx_tipo_situacao' => 'Devolvida ao Autor',
               'sg_casa_situacao' => 'CD',
               'sg_status_situacao' => 'E',
            ],
            [
               'co_tipo_situacao' => 1292,
               'tx_tipo_situacao' => 'Perdeu a Eficácia',
               'sg_casa_situacao' => 'CD',
               'sg_status_situacao' => 'E',
            ],
            [
               'co_tipo_situacao' => 950,
               'tx_tipo_situacao' => 'Retirado pelo Autor',
               'sg_casa_situacao' => 'CD',
               'sg_status_situacao' => 'E',
            ],
            [
               'co_tipo_situacao' => 937,
               'tx_tipo_situacao' => 'Vetado totalmente',
               'sg_casa_situacao' => 'CD',
               'sg_status_situacao' => 'E',
            ],
            [
               'co_tipo_situacao' => 1052,
               'tx_tipo_situacao' => 'Aguardando Abertura de Prazo para Recurso',
               'sg_casa_situacao' => 'CD',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 1180,
               'tx_tipo_situacao' => 'Aguardando Apoiamento',
               'sg_casa_situacao' => 'CD',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 939,
               'tx_tipo_situacao' => 'Aguardando Apreciação do Veto',
               'sg_casa_situacao' => 'CD',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 926,
               'tx_tipo_situacao' => 'Aguardando Apreciação pelo Senado Federal',
               'sg_casa_situacao' => 'CD',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 900,
               'tx_tipo_situacao' => 'Aguardando Autógrafos na Mesa',
               'sg_casa_situacao' => 'CD',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 901,
               'tx_tipo_situacao' => 'Aguardando Constituição de Comissão Temporária',
               'sg_casa_situacao' => 'CD',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 902,
               'tx_tipo_situacao' => 'Aguardando Criação de Comissão Temporária',
               'sg_casa_situacao' => 'CD',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 903,
               'tx_tipo_situacao' => 'Aguardando Deliberação',
               'sg_casa_situacao' => 'CD',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 904,
               'tx_tipo_situacao' => 'Aguardando Deliberação de Recurso',
               'sg_casa_situacao' => 'CD',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 920,
               'tx_tipo_situacao' => 'Aguardando Deliberação do Presidente',
               'sg_casa_situacao' => 'CD',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 907,
               'tx_tipo_situacao' => 'Aguardando Designação de Relator',
               'sg_casa_situacao' => 'CD',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 905,
               'tx_tipo_situacao' => 'Aguardando Despacho do Presidente da Câmara dos Deputados',
               'sg_casa_situacao' => 'CD',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 1296,
               'tx_tipo_situacao' => 'Aguardando Eleição do Presidente da Comissão Especial e do Relator',
               'sg_casa_situacao' => 'CD',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 1070,
               'tx_tipo_situacao' => 'Aguardando Envio ao Executivo',
               'sg_casa_situacao' => 'CD',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 1293,
               'tx_tipo_situacao' => 'Aguardando Envio ao Senado Federal',
               'sg_casa_situacao' => 'CD',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 911,
               'tx_tipo_situacao' => 'Aguardando Instalação de Comissão Temporária',
               'sg_casa_situacao' => 'CD',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 1301,
               'tx_tipo_situacao' => 'Aguardando Interstício Regimental',
               'sg_casa_situacao' => 'CD',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 1300,
               'tx_tipo_situacao' => 'Aguardando Leitura do Parecer da Comissão Especial',
               'sg_casa_situacao' => 'CD',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 1298,
               'tx_tipo_situacao' => 'Aguardando Manifestação do(a) Acusado(a)',
               'sg_casa_situacao' => 'CD',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 915,
               'tx_tipo_situacao' => 'Aguardando Parecer',
               'sg_casa_situacao' => 'CD',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 1170,
               'tx_tipo_situacao' => 'Aguardando Parecer - Ag. devolução Relator não-membro',
               'sg_casa_situacao' => 'CD',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 1297,
               'tx_tipo_situacao' => 'Aguardando Parecer da Comissão Especial',
               'sg_casa_situacao' => 'CD',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 918,
               'tx_tipo_situacao' => 'Aguardando Recurso',
               'sg_casa_situacao' => 'CD',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 1295,
               'tx_tipo_situacao' => 'Aguardando Refornulação de Parecer',
               'sg_casa_situacao' => 'CD',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 921,
               'tx_tipo_situacao' => 'Aguardando Resposta',
               'sg_casa_situacao' => 'CD',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 1310,
               'tx_tipo_situacao' => 'Em tramitação no Conselho de Ética',
               'sg_casa_situacao' => 'CD',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 1303,
               'tx_tipo_situacao' => 'Enviada ao Senado Federal',
               'sg_casa_situacao' => 'CD',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 924,
               'tx_tipo_situacao' => 'Pronta para Pauta',
               'sg_casa_situacao' => 'CD',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 925,
               'tx_tipo_situacao' => 'Tramitando em Conjunto',
               'sg_casa_situacao' => 'CD',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 1294,
               'tx_tipo_situacao' => 'Aguardando Promulgação',
               'sg_casa_situacao' => 'CD',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 1302,
               'tx_tipo_situacao' => 'Aguardando Publicação',
               'sg_casa_situacao' => 'CD',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 1160,
               'tx_tipo_situacao' => 'Aguardando Remessa à Sanção',
               'sg_casa_situacao' => 'CD',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 1150,
               'tx_tipo_situacao' => 'Aguardando Sanção',
               'sg_casa_situacao' => 'CD',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 922,
               'tx_tipo_situacao' => 'Aguardando Vistas',
               'sg_casa_situacao' => 'CD',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 1299,
               'tx_tipo_situacao' => 'Enviada ao Congresso Nacional',
               'sg_casa_situacao' => 'CD',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 1305,
               'tx_tipo_situacao' => 'Enviada ao TCU',
               'sg_casa_situacao' => 'CD',
               'sg_status_situacao' => 'T',
            ],
            [
               'co_tipo_situacao' => 1230,
               'tx_tipo_situacao' => 'Transformado em nova proposição',
               'sg_casa_situacao' => 'CD',
               'sg_status_situacao' => 'T',
            ],
            [
                'co_tipo_situacao' => 9,
                'tx_tipo_situacao' => 'AGUARDANDO INSTALAÇÃO DA COMISSÃO',
                'sg_casa_situacao' => 'SF',
                'sg_status_situacao' => 'T'
            ],
            [
                'co_tipo_situacao' => 10,
                'tx_tipo_situacao' => 'AGUARDANDO DESIGNAÇÃO MEMBROS COMISSÃO',
                'sg_casa_situacao' => 'SF',
                'sg_status_situacao' => 'T'
            ],
            [
                'co_tipo_situacao' => 13,
                'tx_tipo_situacao' => 'AGUARDANDO LEITURA',
                'sg_casa_situacao' => 'SF',
                'sg_status_situacao' => 'T'
            ],
            [
                'co_tipo_situacao' => 16,
                'tx_tipo_situacao' => 'AGUARDANDO DECISÃO DA MESA',
                'sg_casa_situacao' => 'SF',
                'sg_status_situacao' => 'T'
            ],
            [
                'co_tipo_situacao' => 34,
                'tx_tipo_situacao' => 'COMISSÃO CONCLUIDA',
                'sg_casa_situacao' => 'SF',
                'sg_status_situacao' => 'T'
            ],
            [
                'co_tipo_situacao' => 54,
                'tx_tipo_situacao' => 'REMETIDA AO GABINETE CIVIL',
                'sg_casa_situacao' => 'SF',
                'sg_status_situacao' => 'T'
            ],
            [
                'co_tipo_situacao' => 82,
                'tx_tipo_situacao' => 'AGUARDANDO DOCUMENTAÇÃO COMPLEMENTAR SOLICITADA',
                'sg_casa_situacao' => 'SF',
                'sg_status_situacao' => 'T'
            ],
            [
                'co_tipo_situacao' => 86,
                'tx_tipo_situacao' => 'AGENDADA PARA ORDEM DO DIA',
                'sg_casa_situacao' => 'SF',
                'sg_status_situacao' => 'T'
            ],
            [
                'co_tipo_situacao' => 88,
                'tx_tipo_situacao' => 'AGUARDANDO RECEBIMENTO DE EMENDAS PERANTE A MESA',
                'sg_casa_situacao' => 'SF',
                'sg_status_situacao' => 'T'
            ],
            [
                'co_tipo_situacao' => 95,
                'tx_tipo_situacao' => 'AGUARDANDO INCLUSÃO ORDEM DO DIA DE REQUERIMENTO',
                'sg_casa_situacao' => 'SF',
                'sg_status_situacao' => 'T'
            ],
            [
                'co_tipo_situacao' => 100,
                'tx_tipo_situacao' => 'AGUARDANDO INFORMAÇÕES COMPLEMENTARES',
                'sg_casa_situacao' => 'SF',
                'sg_status_situacao' => 'T'
            ],
            [
                'co_tipo_situacao' => 104,
                'tx_tipo_situacao' => 'EM EXAME TÉCNICO PRELIMINAR',
                'sg_casa_situacao' => 'SF',
                'sg_status_situacao' => 'T'
            ],
            [
                'co_tipo_situacao' => 106,
                'tx_tipo_situacao' => 'AGUARDANDO PARECER (CN)',
                'sg_casa_situacao' => 'SF',
                'sg_status_situacao' => 'T'
            ],
            [
                'co_tipo_situacao' => 110,
                'tx_tipo_situacao' => 'AUDIÊNCIA PÚBLICA',
                'sg_casa_situacao' => 'SF',
                'sg_status_situacao' => 'T'
            ],
            [
                'co_tipo_situacao' => 111,
                'tx_tipo_situacao' => 'DEPOIMENTO',
                'sg_casa_situacao' => 'SF',
                'sg_status_situacao' => 'T'
            ],
            [
                'co_tipo_situacao' => 112,
                'tx_tipo_situacao' => 'COMPARECIMENTO',
                'sg_casa_situacao' => 'SF',
                'sg_status_situacao' => 'T'
            ],
            [
                'co_tipo_situacao' => 113,
                'tx_tipo_situacao' => 'APROVADO O SUBSTITUTIVO',
                'sg_casa_situacao' => 'SF',
                'sg_status_situacao' => 'T'
            ],
            [
                'co_tipo_situacao' => 115,
                'tx_tipo_situacao' => 'AUTUAÇÃO FINALIZADA',
                'sg_casa_situacao' => 'SF',
                'sg_status_situacao' => 'T'
            ],
            [
                'co_tipo_situacao' => 116,
                'tx_tipo_situacao' => 'LICENÇA PRÉVIA DEFERIDA',
                'sg_casa_situacao' => 'SF',
                'sg_status_situacao' => 'T'
            ],
            [
                'co_tipo_situacao' => 117,
                'tx_tipo_situacao' => 'LICENÇA PRÉVIA INDEFERIDA',
                'sg_casa_situacao' => 'SF',
                'sg_status_situacao' => 'T'
            ],
            [
                'co_tipo_situacao' => 118,
                'tx_tipo_situacao' => 'AGUARDANDO LEITURA DE REQUERIMENTO',
                'sg_casa_situacao' => 'SF',
                'sg_status_situacao' => 'T'
            ],
            [
                'co_tipo_situacao' => 119,
                'tx_tipo_situacao' => 'APROVADO PARECER NO CONSELHO',
                'sg_casa_situacao' => 'SF',
                'sg_status_situacao' => 'T'
            ],
            [
                'co_tipo_situacao' => 121,
                'tx_tipo_situacao' => 'AGUARDANDO TURNO SUPLEMENTAR EM APRECIAÇÃO TERMINATIVA',
                'sg_casa_situacao' => 'SF',
                'sg_status_situacao' => 'T'
            ],
            [
                'co_tipo_situacao' => 122,
                'tx_tipo_situacao' => 'APROVADO O PROJETO DE LEI DE CONVERSÃO',
                'sg_casa_situacao' => 'SF',
                'sg_status_situacao' => 'T'
            ],
            [
                'co_tipo_situacao' => 124,
                'tx_tipo_situacao' => 'APROVADA A MEDIDA PROVISÓRIA',
                'sg_casa_situacao' => 'SF',
                'sg_status_situacao' => 'T'
            ],
            [
                'co_tipo_situacao' => 126,
                'tx_tipo_situacao' => 'AGENDADO REQUERIMENTO PARA A ORDEM DO DIA',
                'sg_casa_situacao' => 'SF',
                'sg_status_situacao' => 'T'
            ],
            [
                'co_tipo_situacao' => 128,
                'tx_tipo_situacao' => 'PRONTA PARA A PAUTA NO CONSELHO',
                'sg_casa_situacao' => 'SF',
                'sg_status_situacao' => 'T'
            ],
            [
                'co_tipo_situacao' => 129,
                'tx_tipo_situacao' => 'AUTOS ENCAMINHADOS À CONCLUSÃO',
                'sg_casa_situacao' => 'SF',
                'sg_status_situacao' => 'T'
            ],
            [
                'co_tipo_situacao' => 130,
                'tx_tipo_situacao' => 'SESSÃO REALIZADA',
                'sg_casa_situacao' => 'SF',
                'sg_status_situacao' => 'T'
            ],
            [
                'co_tipo_situacao' => 131,
                'tx_tipo_situacao' => 'HOMENAGEM REALIZADA',
                'sg_casa_situacao' => 'SF',
                'sg_status_situacao' => 'T'
            ],
            [
                'co_tipo_situacao' => 132,
                'tx_tipo_situacao' => 'APROVADA(S) EMENDA(S) DO SENADO FEDERAL',
                'sg_casa_situacao' => 'SF',
                'sg_status_situacao' => 'T'
            ],
            [
                 'co_tipo_situacao' => 133,
                'tx_tipo_situacao' => 'REJEITADA(S) EMENDA(S) DO SENADO FEDERAL',
                'sg_casa_situacao' => 'SF',
                'sg_status_situacao' => 'T'
            ],
            [
                'co_tipo_situacao' => 134,
                'tx_tipo_situacao' => 'PROJETO DE LEI DE CONVERSÃO REMETIDO À CÂMARA DOS DEPUTADOS',
                'sg_casa_situacao' => 'SF',
                'sg_status_situacao' => 'T'
            ],
            [
                'co_tipo_situacao' => 135,
                'tx_tipo_situacao' => 'MEDIDA PROVISÓRIA ENVIADA À CÂMARA DOS DEPUTADOS',
                'sg_casa_situacao' => 'SF',
                'sg_status_situacao' => 'T'
            ],
            [
                'co_tipo_situacao' => 137,
                'tx_tipo_situacao' => 'ARQUIVADA',
                'sg_casa_situacao' => 'SF',
                'sg_status_situacao' => 'E'
            ],
            [
                'co_tipo_situacao' => 140,
                'tx_tipo_situacao' => 'APROVADO O REQUERIMENTO',
                'sg_casa_situacao' => 'SF',
                'sg_status_situacao' => 'T'
            ],
            [
                'co_tipo_situacao' => 142,
                'tx_tipo_situacao' => 'AGUARDANDO DECISÃO DA CÂMARA DOS DEPUTADOS',
                'sg_casa_situacao' => 'SF',
                'sg_status_situacao' => 'T'
            ],
            [
                'co_tipo_situacao' => 143,
                'tx_tipo_situacao' => 'CPI EXTINTA FINAL DA LEGISLATURA',
                'sg_casa_situacao' => 'SF',
                'sg_status_situacao' => 'T'
            ],
            [
                'co_tipo_situacao' => 144,
                'tx_tipo_situacao' => 'PREJUDICADA AO FINAL DA LEGISLATURA',
                'sg_casa_situacao' => 'SF',
                'sg_status_situacao' => 'T'
            ],
            [
                'co_tipo_situacao' => 145,
                'tx_tipo_situacao' => 'APROVADA \"AD REFERENDUM\" DA MESA',
                'sg_casa_situacao' => 'SF',
                'sg_status_situacao' => 'T'
            ],
            [
                'co_tipo_situacao' => 148,
                'tx_tipo_situacao' => 'MATÉRIA EM TRAMITAÇÃO',
                'sg_casa_situacao' => 'SF',
                'sg_status_situacao' => 'T'
            ],
            [
                'co_tipo_situacao' => 175,
                'tx_tipo_situacao' => 'AGUARDANDO DESPACHO',
                'sg_casa_situacao' => 'SF',
                'sg_status_situacao' => 'T'
            ],
            [
                'co_tipo_situacao' => 177,
                'tx_tipo_situacao' => 'MATÉRIA DESPACHADA',
                'sg_casa_situacao' => 'SF',
                'sg_status_situacao' => 'T'
            ],
            [
                'co_tipo_situacao' => 180,
                'tx_tipo_situacao' => 'AGUARDANDO PROVIDÊNCIAS',
                'sg_casa_situacao' => 'SF',
                'sg_status_situacao' => 'T'
            ]
        ];

        foreach ($tipos_situacao as $tipo_situacao) {
            $this->tipoSituacaoRepository->firstOrCreate($tipo_situacao);
        }
    }
}